### PR TITLE
specify the base dir and listening address

### PR DESCRIPTION
**Pull request by sacr0**
@b4ldr created new PR. Tried something with the spec file, although not sure what you expect :)

### CODE REVIEW

**Comment by b4ldr** [comment]
version 0.4.0 has been released which includes these changes, thanks

**Comment by b4ldr** [comment]
oh i forgot to say i simplified the [sqlite creation test](https://github.com/icann-dns/puppet-opendnssec/blob/master/manifests/init.pp#L117) let me know if you see issues

**Comment by b4ldr** [comment]
FYI i have now released a 1.0.0 version which uses hiera V5 data source instead of inheriting `params`

**Comment by sacr0** [comment]
@b4ldr great! although with this new hiera setup we are having some issues changes the base_path so variables like sqlite_file have a different path... we'll keep you posted :)

**Pull request closed without merging**
